const fs = require('fs');
const path = require('path');

const mockDataPath = path.join(__dirname, 'src', 'data', 'mockData.ts');
let content = fs.readFileSync(mockDataPath, 'utf8');

const newProviders = `export const providers = [
  {
    id: 'happy-paws-veterinary-hospital',
    name: 'Happy Paws Veterinary Hospital',
    type: 'Veterinary Clinic',
    image: 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=500&h=500&fit=crop',
    rating: 4.8,
    reviews: 124,
    distance: 1.8,
    address: '14th Main Rd, HSR Layout, Bengaluru, Karnataka 560102',
    isOpen: true,
    hours: '9:00 AM - 9:00 PM',
    services: ['Consultation', 'Emergency care', 'Diagnostics', 'Surgery', 'Vaccination'],
    animals: ['Dogs', 'Cats', 'Birds'],
    hasEmergency: true,
    hasAmbulance: true,
    contact: '+91 9876543210'
  },
  {
    id: 'cupa-animal-rescue-center',
    name: 'CUPA Animal Rescue Center',
    type: 'NGO / Rescue',
    image: 'https://images.unsplash.com/photo-1541364983171-a8ba01e95cfc?w=500&h=500&fit=crop',
    rating: 4.9,
    reviews: 312,
    distance: 4.2,
    address: 'Koramangala, Bengaluru, Karnataka 560034',
    isOpen: true,
    hours: '24/7',
    services: ['Rescue', 'Shelter', 'Emergency care', 'Adoption'],
    animals: ['Dogs', 'Cats', 'Cows', 'Birds'],
    hasEmergency: true,
    hasAmbulance: true,
    contact: '+91 8765432109'
  },
  {
    id: 'indiranagar-pet-clinic',
    name: 'Indiranagar Pet Clinic',
    type: 'Veterinary Clinic',
    image: 'https://images.unsplash.com/photo-1628009368231-7710bfb72a6b?w=500&h=500&fit=crop',
    rating: 4.5,
    reviews: 89,
    distance: 5.6,
    address: '100 Feet Rd, Indiranagar, Bengaluru, Karnataka 560038',
    isOpen: false,
    hours: '10:00 AM - 8:00 PM',
    services: ['Consultation', 'Vaccination', 'Grooming'],
    animals: ['Dogs', 'Cats'],
    hasEmergency: false,
    hasAmbulance: false,
    contact: '+91 7654321098'
  },
  {
    id: 'blue-cross-veterinary-emergency',
    name: 'Blue Cross Veterinary Emergency',
    type: 'Emergency Hospital',
    image: 'https://images.unsplash.com/photo-1576201836106-db1758fd1c97?w=500&h=500&fit=crop',
    rating: 4.7,
    reviews: 201,
    distance: 3.1,
    address: 'Jayanagar 4th Block, Bengaluru, Karnataka 560011',
    isOpen: true,
    hours: '24/7',
    services: ['Emergency care', 'Surgery', 'Diagnostics', 'ICU'],
    animals: ['Dogs', 'Cats', 'Small Pets'],
    hasEmergency: true,
    hasAmbulance: true,
    contact: '+91 9988776655'
  },
  {
    id: 'pawz-boarding-daycare',
    name: 'Pawz Boarding & Daycare',
    type: 'Boarding',
    image: 'https://images.unsplash.com/photo-1601758174114-e711c0cbaaa7?w=500&h=500&fit=crop',
    rating: 4.6,
    reviews: 67,
    distance: 2.4,
    address: 'BTM Layout, Bengaluru, Karnataka 560068',
    isOpen: true,
    hours: '8:00 AM - 8:00 PM',
    services: ['Boarding', 'Daycare', 'Grooming'],
    animals: ['Dogs', 'Cats'],
    hasEmergency: false,
    hasAmbulance: false,
    contact: '+91 8877665544'
  },
  {
    id: 'quick-response-pet-ambulance',
    name: 'Quick Response Pet Ambulance',
    type: 'Ambulance',
    image: 'https://images.unsplash.com/photo-1517677122409-e85d1e2f89bb?w=500&h=500&fit=crop',
    rating: 4.8,
    reviews: 145,
    distance: 0.5,
    address: 'Serving all Bengaluru (Based in Koramangala)',
    isOpen: true,
    hours: '24/7',
    services: ['Transport', 'Emergency Transport', 'Oxygen Support'],
    animals: ['Dogs', 'Cats', 'Large Animals'],
    hasEmergency: true,
    hasAmbulance: true,
    contact: '+91 7766554433'
  },
  {
    id: 'whitefield-avian-exotic-clinic',
    name: 'Whitefield Avian & Exotic Clinic',
    type: 'Veterinary Clinic',
    image: 'https://images.unsplash.com/photo-1551730459-92db2a308d6a?w=500&h=500&fit=crop',
    rating: 4.9,
    reviews: 78,
    distance: 8.2,
    address: 'Whitefield Main Road, Bengaluru',
    isOpen: true,
    hours: '10:00 AM - 7:00 PM',
    services: ['Exotic Pet Care', 'Avian Care', 'Diagnostics'],
    animals: ['Birds', 'Reptiles', 'Small Pets'],
    hasEmergency: false,
    hasAmbulance: false,
    contact: '+91 9900112233'
  },
  {
    id: 'marathahalli-24x7-pet-hospital',
    name: 'Marathahalli 24x7 Pet Hospital',
    type: 'Emergency Hospital',
    image: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=500&h=500&fit=crop',
    rating: 4.5,
    reviews: 156,
    distance: 6.5,
    address: 'Outer Ring Road, Marathahalli, Bengaluru',
    isOpen: true,
    hours: '24/7',
    services: ['Emergency Care', 'Surgery', 'ICU'],
    animals: ['Dogs', 'Cats'],
    hasEmergency: true,
    hasAmbulance: false,
    contact: '+91 8899001122'
  },
  {
    id: 'tails-trails-boarding',
    name: 'Tails & Trails Boarding',
    type: 'Boarding',
    image: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=500&h=500&fit=crop',
    rating: 4.7,
    reviews: 92,
    distance: 12.0,
    address: 'Sarjapur Road, Bengaluru',
    isOpen: true,
    hours: '8:00 AM - 6:00 PM',
    services: ['Boarding', 'Play Areas', 'Training'],
    animals: ['Dogs'],
    hasEmergency: false,
    hasAmbulance: false,
    contact: '+91 7788990011'
  },
  {
    id: 'compassion-unlimited-ambulance',
    name: 'Compassion Unlimited Pet Ambulance',
    type: 'Ambulance',
    image: 'https://images.unsplash.com/photo-1584813470613-5b1c1cad3d69?w=500&h=500&fit=crop',
    rating: 4.8,
    reviews: 45,
    distance: 2.1,
    address: 'Serving all Bengaluru (Based in Jayanagar)',
    isOpen: true,
    hours: '24/7',
    services: ['Emergency Transport', 'First Aid'],
    animals: ['Dogs', 'Cats', 'Birds'],
    hasEmergency: true,
    hasAmbulance: true,
    contact: '+91 6677889900'
  },
  {
    id: 'charlies-animal-rescue-centre-care',
    name: 'Charlies Animal Rescue Centre (CARE)',
    type: 'NGO / Rescue',
    image: 'https://images.unsplash.com/photo-1593871131758-29938b368798?w=500&h=500&fit=crop',
    rating: 4.9,
    reviews: 420,
    distance: 9.5,
    address: 'Yelahanka, Bengaluru',
    isOpen: true,
    hours: '9:00 AM - 5:00 PM',
    services: ['Rescue', 'Shelter', 'Adoption', 'Rehabilitation'],
    animals: ['Dogs', 'Cats', 'Farm Animals', 'Birds'],
    hasEmergency: true,
    hasAmbulance: true,
    contact: '+91 5566778899'
  }
];`;

content = content.replace(/export const providers = \[[\s\S]*?\];/, newProviders);

fs.writeFileSync(mockDataPath, content, 'utf8');
